### ISSUE TITLE
Old logo in organisation

### ISSUE THREAD

**Issue by erikvansebille** [UU-IMAU/Python-for-lunch-Notebooks#7]
When I wanted to share the link to this repo in a discussion we had about Open Science in teaching, I saw that the IMAU organisation here on github still has the old logo. Would be good to update this at some point to the new logo? Not sure where to find that logo, though

**Comment by arthuroldeman** [comment]
There is a few new IMAU logo styles in the IMAU Teams under Files. But it is the rectangular, landscape style. I have also attached a circular form. Sandra has more of these, also a .psd so that you can put any text (f.e. 'IMAU' instead of the full name). 

![UU-IMAU_social_media_avatar](https://user-images.githubusercontent.com/57496273/98942087-c96ac980-24ed-11eb-8150-0db2ad8233bc.png)

**Comment by erikvansebille** [comment]
Thanks @arthuroldeman. I don't think I have permissions to update the logo of the UU-IMAU organisation here. Who does?

**Comment by lvankampenhout** [comment]
I've just changed the logo. Thanks for letting me know @erikvansebille 
On another note, I will make you maintainer for the institute.
